### ISSUE TITLE
docker image with neurodocker

### ISSUE THREAD

**Issue by kaczmarj** [pnlbwh/pnlNipype#31]
hello, this project can use neurodocker to generate a docker image or singularity image with the required dependencies.

```
docker run --rm kaczmarj/neurodocker:0.6.0 generate docker \
  --base=neurodebian:stretch-non-free --pkg-manager=apt \
  --freesurfer version=6.0.1 \
  --ants version=2.3.0 \
  --install dcm2niix fsl \
  --miniconda use_env=base conda_install="python=3.7"
```

this does not install UKFTractography but i can add that. let me know if you would be interested in me adding this as a PR to this project.

**Comment by tashrifbillah** [comment]
Hi @kaczmarj , I have already developed docker image for our [pnlpipe](https://pnlbwh.github.io/pnlpipe-containers/). It is being tested by our collaborators out of the country. Once we obtain feedback, I shall develop containers, docker and singularity, for pnlNipype as well.

When I started developing the containers, I didn't use neurodocker because, rather primitive Centos7 for having more control on building my virtual machine.

You may find a few of my containers [here](https://hub.docker.com/u/tbillah).

I can work around your idea in a few weeks.

**Comment by kaczmarj** [comment]
hi @tashrifbillah - that makes sense. thanks for the reply. for what it's worth, you can use neurodocker to build on centos:7 as well, but i do understand that you want more fine-grained control over your images.

**Comment by tashrifbillah** [comment]
Hi @kaczmarj , I forgot to reply here, I created a CentOS 7 based docker image about a year ago.
https://hub.docker.com/r/tbillah/pnlpipe

**Comment by kaczmarj** [comment]
Thanks for the reply @tashrifbillah ! i'll close this
